# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oghnK_CrKztW8dylUrEz8b_HewrUOM9
"""

#ejercicio 1
precios = [120, 45, 80, 150, 30, 200, 95]
precios_vip = [p - 10 for p in precios if p >= 100]
print(precios_vip)
#ejercicio 2
letras = ["a", "b", "c", "d", "e", "f", "g", "h"]
print(letras[2:6])
print(letras[::-1])

"""Responde:
1. ¿Qué hace lista[::-1]? :
  invierte la lista.
2. Escribe una comprensión que genere los primeros 10 números pares. :
  num = [x for x in range(1, 21) if x % 2 == 0]
3. ¿Qué hace nums[2:7]? ¿Se incluye el índice 7? :
  muestra los numeros desde la posicion 2 en el indice hasta el 6, el 7 no cuenta.
"""