# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJbhm92rP8hMecPNLHOUaJ1QP0Jh_uaV
"""

# ===== SLICING =====
numeros = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
print("Lista original:", numeros)

# Desde índice 2 hasta el 5 (el 5 NO se incluye)
print("numeros[2:6]:", numeros[2:6])

# Desde el 3 hasta el final
print("numeros[3:]:", numeros[3:])

# Hasta el índice 5 (excluye índice 5)
print("numeros[:5]:", numeros[:5])

# Últimos 3 elementos
print("numeros[-3:]:", numeros[-3:])

# Cada 2 elementos
print("numeros[::2]:", numeros[::2])

# Invertir toda la lista
print("numeros[::-1]:", numeros[::-1])

# ===== COMPRENSIÓN DE LISTAS =====
# Cuadrados del 0 al 9
cuadrados = [x**2 for x in range(10)]
print("Cuadrados:", cuadrados)

# Números pares del 0 al 19
pares = [x for x in range(20) if x % 2 == 0]
print("Pares:", pares)

# Palabras a mayúsculas
frutas = ["manzana", "banana", "cereza"]
mayusculas = [fruta.upper() for fruta in frutas]
print("Mayúsculas:", mayusculas)

# Con condición if-else
clasificacion = ["par" if x % 2 == 0 else "impar" for x in range(10)]
print("Clasificación:", clasificacion)

#EJERCICIO 1
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#a)
print(nums[:5])
#b)
print(nums[-4:])
#c)
print(nums[1:6])
#d)
print(nums[::-1])
#e)
print(nums[::-2])

#EJERCICIO 2
#a)
num = [x**2 for x in range(16)]
print(num)
n1 = [x for x in range(1, 31) if x % 3 == 0]
print(n1)

#EJERCICIO 3
palabras = ["sol", "luna", "estrella", "cielo"]
#a)
mayus = [p.upper() for p in palabras]
#b)
largas = [p for p in palabras if len(p) > 4]