# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAjj7bUq2j7lcMHMdWB85GPNejO_UuiW
"""

#ejericico1
tareas = ["estudiar", "entrenar", "comprar", "leer"]
for t in tareas:
  print(f"- {tareas}")
#ejericico2
ventas = [120, 450, 300, 890, 150]
suma = 0
for v in ventas:
  suma += v
promedio = suma /len(ventas)
print(f"suma {suma} y promedio: {promedio}")
#ejercicio3
tareas = ["estudiar", "entrenar", "comprar", "leer"]
for i,t in enumerate(tareas):
  print(f"{i}. {t}")
#EJERCICIO4
Celsius = [0, 10, 20, 35, 42]
farenheit = [(c * 9/5) + 32 for c in celsius if c > 15]
print(farenheit)

"""1. ¿Qué hace lista[::-1]?
  convierte la lista al inverso
2. Escribe una comprensión que genere los primeros 10 números pares.
  uso range, for n in range(21) if n % 2 == 0
3. ¿Qué hace nums[2:7]? ¿Se incluye el índice 7?
  muestra los numeros de el 2 al 6
"""